"""
Django settings for knowledgebase project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import logging

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&qc&k!l4cjs9o2q#u0^6(iiyqtym)cm=cf0*b+(4!$4ij!$k+w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'knowledge',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'knowledgebase.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': False,#false: 不再允许django按照默认方式寻找模板文件
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'knowledgebase.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'knowledgebase',
        'USER': 'root',
        'PASSWORD': 'abc123!!',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

# STATIC_URL = '/home/hzf/pythonPrj/knowledgebase/static/'
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(levelname)s %(asctime)s %(pathname)s %(filename)s %(module)s %(funcName)s %(lineno)d: %(message)s'
        },  # 对日志信息进行格式化，每个字段对应了日志格式中的一个字段，更多字段参考官网文档，我认为这些字段比较合适，输出类似于下面的内容
        # INFO 2016-09-03 16:25:20,067 /home/ubuntu/mysite/views.py views.py views get 29: some info...
    },
    'handlers': {
        # 'file': {
        #     'level': 'DEBUG',
        #     'class': 'logging.FileHandler',
        #     'filename': '/home/hzf/pythonPrj/knowledgebase/error.log',
        # },
        'dbsql':{
             #'level': 'DEBUG',
             #'class': 'logging.StreamHandler',
             'class': 'logging.FileHandler',
             'filename': '/home/hzf/pythonPrj/knowledgebase/dbsql.log',
        },
        'django':{
             #'level': 'DEBUG',
             #'class': 'logging.StreamHandler',
             'class': 'logging.FileHandler',
             'filename': '/home/hzf/pythonPrj/knowledgebase/django.log',
        },
        'django.request':{
             #'level': 'DEBUG',
             #'class': 'logging.StreamHandler',
             'class': 'logging.FileHandler',
             'filename': '/home/hzf/pythonPrj/knowledgebase/django.request.log',
        },
        'django.security':{
             #'level': 'DEBUG',
             #'class': 'logging.StreamHandler',
             'class': 'logging.FileHandler',
             'filename': '/home/hzf/pythonPrj/knowledgebase/django.security.log',
        }
        # 'console':{
        #     'level': 'DEBUG',
        #     'class': 'logging.StreamHandler',
        #     #'formatter': 'standard'
        # },
        # 'dbsql': {
        #     'level': 'DEBUG',
        #     'class': 'logging.StreamHandler',
        #     'filename': '/home/hzf/pythonPrj/knowledgebase/dbsql.log',
        # },
    },
    'loggers': {
        # 'django.request': {
        #     'handlers': ['dbsql'],
        #     'level': 'DEBUG',
        #     'propagate': True,
        # },
        'django':{
            'handlers': ['django'],
            #'level': 'DEBUG',
            'propagate': True,
        },
        'django.request':{
            'handlers': ['django.request'],
            #'level': 'DEBUG',
            'propagate': True,
        },
        'django.db.backends': {  # 打印数据库脚本
            'handlers': ['dbsql'],
            #'level': 'DEBUG',
            'propagate': True,
        },
        'django.security.*': {
            'handlers': ['django.security'],
            #'level': 'DEBUG',
            'propagate': True,
        },
    },
}
